apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngdock-deployment
spec:
  selector:
    matchLabels:
      app: ngdock-pod
  template:
    metadata:
      labels:
        app: ngdock-pod
    spec:
      containers:
        - name: ngdock-container
          image: dattaranit/newangulardocker:v2
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
